In [5]:
import numpy as np

# Create random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Print array shape
print("Array shape:", reshaped_array.shape)

# Print array
print("Array :")
print(reshaped_array)

# Replace the max in each row by 0
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

print("Array after replacing max in each row by 0:")
print(reshaped_array)

# Create a 2-dimensional array of size 4 x 3 with 4-byte integer elements
array_4x3 = np.random.randint(0, 1000, size=(4, 3), dtype=np.int32)

# Print shape, type, and data type of the array
print("\nShape of the array:", array_4x3.shape)
print("Type of the array:", type(array_4x3))
print("Data type of the array:", array_4x3.dtype)

Array shape: (3, 5)
Array :
[[19 11 15 18 20]
 [ 4 10 15 19 13]
 [17 16 16  4  7]]
Array after replacing max in each row by 0:
[[19 11 15 18  0]
 [ 4 10 15  0 13]
 [ 0 16 16  4  7]]

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array: int32


In [2]:
import numpy as np

# Define the square array
array = np.array([[3, -2],
                  [1, 0]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(array)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nRight Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [3]:
import numpy as np

# Define the array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Compute the sum of diagonal elements
diagonal_sum = np.trace(array)

# Print the sum
print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 4


In [4]:
import numpy as np

# Define the arrays
array1 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Reshape array1 to 3x2
reshaped_array1 = array1.reshape(3, 2)

# Reshape array2 to 2x3
reshaped_array2 = array2.reshape(2, 3)

# Print the reshaped arrays
print("Reshaped array1 (3x2):")
print(reshaped_array1)

print("\nReshaped array2 (2x3):")
print(reshaped_array2)

Reshaped array1 (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array2 (2x3):
[[1 2 3]
 [4 5 6]]
